name: Deploy wp-content to VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'wp-content/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key from raw secret (normalize)
        shell: bash
        run: |
          umask 177
          KEY="${{ secrets.SSH_PRIVATE_KEY }}"
          if echo "$KEY" | grep -q '\\n'; then
            printf "%s" "$KEY" | sed 's/\\r//g; s/\\n/\n/g' > /tmp/ci_key
          else
            printf "%s" "$KEY" > /tmp/ci_key
          fi
          sed -i 's/\r$//' /tmp/ci_key
          chmod 600 /tmp/ci_key
      
      - name: Show key fingerprint (debug)
        run: |
          echo "Fingerprint:"; ssh-keygen -lf /tmp/ci_key
          echo "Derived public key:"; ssh-keygen -y -f /tmp/ci_key
      
      - name: Verify SSH connectivity
        run: |
          ssh -i /tmp/ci_key -p ${{ secrets.SSH_PORT }} \
            -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo SSH_OK'

      
      - name: Rsync wp-content (exclude uploads/cache)
        env:
          RSYNC_EXCLUDES: "--exclude 'uploads' --exclude 'cache' --exclude '.git' --exclude '.github' --exclude 'node_modules'"
        run: |
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            $RSYNC_EXCLUDES \
            -e "ssh -i /tmp/ci_key -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes" \
            --rsync-path="sudo rsync" \
            wp-content/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/wp-content/"

      # 6) Chỉnh quyền & reload PHP-FPM
      - name: Fix permissions & reload services
        run: |
          ssh -i /tmp/ci_key -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo chown -R www-data:www-data '${{ secrets.TARGET_DIR }}/wp-content' && \
             sudo find '${{ secrets.TARGET_DIR }}/wp-content' -type d -exec chmod 755 {} \; && \
             sudo find '${{ secrets.TARGET_DIR }}/wp-content' -type f -exec chmod 644 {} \; && \
             sudo systemctl reload php8.1-fpm || true"
