# 1) Upload themes to tmp (no sudo, robust)
- name: Upload themes to tmp (no sudo)
  shell: bash
  run: |
    set -euo pipefail

    # Chẩn đoán: đảm bảo secrets có giá trị
    echo "Host: '${{ secrets.SSH_HOST }}'  User: '${{ secrets.SSH_USER }}'  Port: '${{ secrets.SSH_PORT }}'"

    # Thư mục tạm ở máy remote (dùng $HOME tránh ~)
    REMOTE_TMP='$HOME/deploy_tmp/themes'

    # Tạo thư mục tạm trên remote
    ssh -o IdentitiesOnly=yes -p "${{ secrets.SSH_PORT }}" \
      "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
      "mkdir -p ${REMOTE_TMP}"

    # Đồng bộ themes lên remote tmp
    rsync -az --delete \
      --omit-dir-times --no-perms --no-owner --no-group \
      --exclude '.git' --exclude '.github' --exclude 'node_modules' \
      -e "ssh -o IdentitiesOnly=yes -p ${{ secrets.SSH_PORT }}" \
      themes/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${REMOTE_TMP}/"

# 2) Move to target with sudo & fix permissions
- name: Move to target with sudo & fix permissions
  shell: bash
  run: |
    set -euo pipefail
    ssh -o IdentitiesOnly=yes -p "${{ secrets.SSH_PORT }}" \
      "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" <<'EOF'
    set -e
    REMOTE_TMP="$HOME/deploy_tmp/themes"
    TARGET_DIR="${TARGET_DIR}"
    TARGET="$TARGET_DIR/wp-content/themes"

    sudo mkdir -p "$TARGET"
    sudo rsync -a --delete "$REMOTE_TMP"/ "$TARGET"/

    sudo chown -R www-data:www-data "$TARGET"
    sudo find "$TARGET" -type d -exec chmod 755 {} \;
    sudo find "$TARGET" -type f -exec chmod 644 {} \;

    sudo systemctl reload php8.1-fpm || sudo systemctl reload php8.2-fpm || true
    sudo systemctl reload nginx || sudo systemctl reload apache2 || true
    EOF
  env:
    TARGET_DIR: ${{ secrets.TARGET_DIR }}
