name: Deploy wp-content to VPS

on:
  push:
    branches: [ "main" ]         # đổi nếu bạn dùng branch khác
    paths:
      - "wp-content/**"          # chỉ chạy khi có thay đổi trong wp-content
  workflow_dispatch: {}           # cho phép chạy tay

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Khởi động ssh-agent & nạp private key (lấy từ secret base64)
      - name: Setup SSH (agent + key)
        shell: bash
        run: |
          set -euo pipefail
          eval "$(ssh-agent -s)"

          mkdir -p ~/.ssh
          # Giải mã secret base64 thành private key
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ci
          chmod 600 ~/.ssh/id_ci
          ssh-add ~/.ssh/id_ci

          # Add host vào known_hosts để StrictHostKeyChecking=yes không chặn
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # 2) Kiểm tra kết nối SSH (debug)
      - name: Test SSH connectivity
        run: |
          ssh -o StrictHostKeyChecking=yes -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            'whoami && hostname'

      # 3) Rsync wp-content (trừ uploads/cache)
      - name: Rsync wp-content (exclude uploads/cache)
        run: |
          RSYNC_EXCLUDES=(
            "--exclude uploads"
            "--exclude cache"
            "--exclude .git"
            "--exclude .github"
            "--exclude node_modules"
          )
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            ${RSYNC_EXCLUDES[@]} \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            wp-content/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/wp-content/"

      # 4) (Tuỳ chọn) Chỉnh quyền & reload PHP-FPM nếu cần
      #   Nếu user của bạn không có quyền ghi vào TARGET_DIR, hãy:
      #   - cấp quyền thư mục cho user đó, hoặc
      #   - thay rsync phía trên bằng --rsync-path="sudo rsync" và cấu hình sudo NOPASSWD cho rsync.
      - name: Fix permissions & reload services (optional)
        if: ${{ env.NEED_POSTFIX == '1' }}
        env:
          NEED_POSTFIX: "0"    # đổi sang "1" nếu muốn chạy khối này
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
          set -e
          TARGET_DIR="${TARGET_DIR}"
          sudo chown -R www-data:www-data "$TARGET_DIR/wp-content"
          sudo find "$TARGET_DIR/wp-content" -type d -exec chmod 755 {} \;
          sudo find "$TARGET_DIR/wp-content" -type f -exec chmod 644 {} \;
          sudo systemctl reload php8.1-fpm || true
          EOF
        env:
          TARGET_DIR: "${{ secrets.TARGET_DIR }}"
