name: Deploy theme to VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'themes/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify SSH connectivity
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "SSH OK"'

      - name: Rsync only themes (use ssh-agent; no -i)
        run: |
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            --exclude='.git' --exclude='.github' --exclude='node_modules' \
            -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes" \
            --rsync-path="sudo rsync" \
            themes/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/wp-content/themes/"

      - name: Fix permissions & reload PHP
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo chown -R www-data:www-data '${{ secrets.TARGET_DIR }}/wp-content/themes' && \
             sudo find '${{ secrets.TARGET_DIR }}/wp-content/themes' -type d -exec chmod 755 {} \; && \
             sudo find '${{ secrets.TARGET_DIR }}/wp-content/themes' -type f -exec chmod 644 {} \; && \
             sudo systemctl reload php8.1-fpm || true"
