name: Deploy wp-content to VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'wp-content/**'          # chỉ chạy khi có thay đổi trong wp-content
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Nếu cần build assets cho theme, mở comment phần này
      # - name: Build theme assets
      #   working-directory: wp-content/themes/vineye
      #   run: |
      #     npm ci
      #     npm run build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # (tuỳ chọn) Kiểm tra SSH
      - name: Verify SSH connectivity
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo SSH_OK'

      - name: Rsync wp-content (exclude uploads/cache)
        env:
          RSYNC_EXCLUDES: "--exclude 'uploads' --exclude 'cache' --exclude '.git' --exclude '.github' --exclude 'node_modules'"
        run: |
           rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            --exclude '.git' --exclude '.github' --exclude 'node_modules' \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            --rsync-path="sudo rsync" \
            themes/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/wp-content/themes/

      - name: Fix permissions & reload services
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo chown -R www-data:www-data '${{ secrets.TARGET_DIR }}/wp-content' && \
             sudo find '${{ secrets.TARGET_DIR }}/wp-content' -type d -exec chmod 755 {} \; && \
             sudo find '${{ secrets.TARGET_DIR }}/wp-content' -type f -exec chmod 644 {} \; && \
             sudo systemctl reload php8.1-fpm || true"
