name: Deploy to VPS

on:
  push:
    branches: [ "main" ]   # đổi branch nếu bạn dùng nhánh khác
  workflow_dispatch: {}     # cho phép bấm chạy tay

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Đồng bộ code sang VPS (TRỪ uploads, cache, .git…)
      - name: Rsync code
        run: |
          RSYNC_EXCLUDES="--exclude '.git' --exclude '.github' --exclude 'node_modules' --exclude '.env' --exclude 'wp-content/uploads' --exclude 'wp-content/cache'"
          rsync -az --delete $RSYNC_EXCLUDES \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/

      # Chạy lệnh sau deploy trên VPS (tuỳ chọn)
      - name: Post-deploy commands
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # quyền file/folder chuẩn
          sudo find /var/www/minhtris.id.vn/peugeot -type d -exec chmod 755 {} \;
          sudo find /var/www/minhtris.id.vn/peugeot -type f -exec chmod 644 {} \;
          sudo chown -R www-data:www-data /var/www/minhtris.id.vn/peugeot

          # (tuỳ) build front-end nếu có
          # cd /var/www/minhtris.id.vn/peugeot/wp-content/themes/ten-theme && npm ci && npm run build

          # reload PHP/Nginx (nhanh, không downtime)
          sudo systemctl reload php8.1-fpm || true
          sudo systemctl reload nginx || true
          EOF
