name: Deploy theme to VPS

on:
  push:
    branches: [ "main" ]
    paths: [ "themes/**" ]          # đổi nếu source của bạn là wp-content/themes/**
  workflow_dispatch: {}

concurrency:
  group: deploy-theme
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup SSH (agent + key from base64)
        shell: bash
        run: |
          set -euo pipefail
          # Kiểm tra secrets bắt buộc
          : "${{ secrets.SSH_KEY_B64?Missing SSH_KEY_B64 }}"
          : "${{ secrets.SSH_HOST?Missing SSH_HOST }}"
          : "${{ secrets.SSH_USER?Missing SSH_USER }}"
          : "${{ secrets.SSH_PORT?Missing SSH_PORT }}"
          : "${{ secrets.TARGET_DIR?Missing TARGET_DIR }}"

          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ci
          chmod 600 ~/.ssh/id_ci
          ssh-add ~/.ssh/id_ci

          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Show key fingerprint (debug)
        run: ssh-keygen -lf ~/.ssh/id_ci

      - name: Test SSH (vvv)
        run: |
          ssh -vvv -o IdentitiesOnly=yes -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" 'whoami && hostname'

      - name: Upload themes to tmp (no sudo)
        shell: bash
        run: |
          set -euo pipefail
          echo "Host='${{ secrets.SSH_HOST }}' User='${{ secrets.SSH_USER }}' Port='${{ secrets.SSH_PORT }}'"
          REMOTE_TMP='$HOME/deploy_tmp/themes'
          ssh -o IdentitiesOnly=yes -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p ${REMOTE_TMP}"
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            --exclude '.git' --exclude '.github' --exclude 'node_modules' \
            -e "ssh -o IdentitiesOnly=yes -p ${{ secrets.SSH_PORT }}" \
            themes/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${REMOTE_TMP}/"

      - name: Move to target with sudo & fix permissions
        shell: bash
        env: { TARGET_DIR: ${{ secrets.TARGET_DIR }} }
        run: |
          set -euo pipefail
          ssh -o IdentitiesOnly=yes -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" <<'EOF'
          set -e
          REMOTE_TMP="$HOME/deploy_tmp/themes"
          TARGET="${TARGET_DIR}/wp-content/themes"

          sudo mkdir -p "$TARGET"
          sudo rsync -a --delete "$REMOTE_TMP"/ "$TARGET"/

          sudo chown -R www-data:www-data "$TARGET"
          sudo find "$TARGET" -type d -exec chmod 755 {} \;
          sudo find "$TARGET" -type f -exec chmod 644 {} \;

          sudo systemctl reload php8.2-fpm || sudo systemctl reload php8.1-fpm || true
          sudo systemctl reload nginx || sudo systemctl reload apache2 || true

          # dọn thư mục tạm
          rm -rf "$REMOTE_TMP"
          EOF
