name: Deploy wp-content to VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'wp-content/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Nếu có build asset cho theme thì bật khối này
      # - name: Build theme assets
      #   working-directory: wp-content/themes/vineye
      #   run: |
      #     npm ci
      #     npm run build

      # Cách chắc chắn: tự khởi động ssh-agent và nạp key đã chuẩn hoá
      - name: Setup SSH (start agent & add key)
        shell: bash
        run: |
          set -euo pipefail
          eval "$(ssh-agent -s)"

          # Trường hợp bạn lỡ lưu secret ở dạng 1 dòng có \n: chuyển \n -> newline.
          # Nếu secret đã đúng dạng đa dòng thì câu lệnh này vẫn an toàn.
          mkdir -p ~/.ssh
          printf '%s' '${{ secrets.SSH_PRIVATE_KEY }}' | sed 's/\\r//g; s/\\n/\n/g' > ~/.ssh/id_ci
          chmod 600 ~/.ssh/id_ci
          ssh-add ~/.ssh/id_ci

          # known_hosts
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Derive public key (debug)
        run: |
          set -e
          ssh-keygen -y -f ~/.ssh/id_ci > /tmp/ci_key.pub
          echo "== BEGIN PUBKEY ==" && cat /tmp/ci_key.pub && echo "== END PUBKEY =="

      - name: Test SSH connectivity
        run: |
          ssh -vvv -o StrictHostKeyChecking=yes -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            'whoami && hostname'

      - name: Rsync wp-content (exclude uploads/cache)
        run: |
          RSYNC_EXCLUDES=(
            "--exclude uploads"
            "--exclude cache"
            "--exclude .git"
            "--exclude .github"
            "--exclude node_modules"
          )
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            ${RSYNC_EXCLUDES[@]} \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            --rsync-path="sudo rsync" \
            wp-content/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/wp-content/"

      - name: Fix permissions & reload services (optional)
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
          set -e
          sudo chown -R www-data:www-data ${TARGET_DIR}/wp-content
          sudo find ${TARGET_DIR}/wp-content -type d -exec chmod 755 {} \;
          sudo find ${TARGET_DIR}/wp-content -type f -exec chmod 644 {} \;
          sudo systemctl reload php8.1-fpm || true
          EOF
        env:
          TARGET_DIR: "${{ secrets.TARGET_DIR }}"
