- name: Setup SSH (agent + key with validation)
  shell: bash
  run: |
    set -euo pipefail
    eval "$(ssh-agent -s)"
    mkdir -p ~/.ssh

    # ƯU TIÊN: lấy key từ SSH_KEY_B64 (private key đã base64)
    if [ -n "${{ secrets.SSH_KEY_B64 }}" ]; then
      echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ci || true
    fi

    # FALLBACK: nếu chưa có file (hoặc rỗng), thử lấy từ SSH_PRIVATE_KEY (đa dòng hoặc 1 dòng có \n)
    if [ ! -s ~/.ssh/id_ci ] && [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
      printf '%s' '${{ secrets.SSH_PRIVATE_KEY }}' | sed 's/\\r//g; s/\\n/\n/g' > ~/.ssh/id_ci
    fi

    # Nếu vẫn chưa có file -> fail sớm
    if [ ! -s ~/.ssh/id_ci ]; then
      echo "No private key material provided. Set SSH_KEY_B64 (preferred) or SSH_PRIVATE_KEY."
      exit 1
    fi

    chmod 600 ~/.ssh/id_ci || true

    echo "== HEADER =="; head -n1 ~/.ssh/id_ci || true
    echo "== FOOTER =="; tail -n2 ~/.ssh/id_ci || true

    echo "== FINGERPRINT (ssh-keygen -lf) =="
    # Kiểm tra định dạng key. Nếu sai -> báo lỗi rõ ràng và dừng.
    ssh-keygen -lf ~/.ssh/id_ci || { 
      echo "Invalid private key file."
      echo "- Đảm bảo bạn dùng PRIVATE key (không phải .pub)."
      echo "- Dòng đầu phải là: -----BEGIN OPENSSH PRIVATE KEY-----"
      echo "- Nếu dùng base64: phải base64 **file private key** nguyên vẹn, không thêm/kém ký tự."
      exit 1
    }

    # Thêm key vào agent
    ssh-add ~/.ssh/id_ci

    # known_hosts để khỏi prompt yes/no
    ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
    chmod 600 ~/.ssh/known_hosts
